/**
 * KDP estimation engine — JavaScript port of the Python engine in
 * kdp_analytics_app.py. Parity is enforced by extension/engine.test.js
 * against extension/expected.json (generated by make_expected.py).
 * No external dependencies; usable in browsers and Node.
 */
(function (root) {
  "use strict";

  var BSR_ANCHORS = [
    [1, 3000],
    [10, 1000],
    [100, 200],
    [500, 70],
    [1000, 35],
    [5000, 12],
    [10000, 7],
    [50000, 2.2],
    [100000, 1.1],
    [250000, 0.5],
    [500000, 0.22],
    [1000000, 0.06],
  ];

  var PRINT_COST_RULES = {
    Paperback: { fixed_low: 2.3, low_max_pages: 110, fixed: 1.0, per_page: 0.012 },
    Hardcover: { fixed_low: 6.8, low_max_pages: 108, fixed: 5.65, per_page: 0.012 },
  };

  var STOPWORDS = new Set(
    "a an and are as at be been being but by can could did do does for from had has have he her his how i if in into is it its me more most my no not of on or our out over so some than that the their them then there these they this to too under up us was we were what when where which who why will with you your".split(
      /\s+/
    )
  );

  var SOURCE_WEIGHTS = { Title: 1.0, Subtitle: 0.7, Category: 0.5 };

  function estimateDailySales(bsr) {
    if (bsr === null || bsr === undefined || bsr <= 0) return 0.0;
    if (bsr <= BSR_ANCHORS[0][0]) return BSR_ANCHORS[0][1];
    if (bsr >= BSR_ANCHORS[BSR_ANCHORS.length - 1][0]) {
      var last = BSR_ANCHORS[BSR_ANCHORS.length - 1];
      var lastRank = last[0];
      var lastSales = last[1];
      return Math.max(lastSales * Math.pow(lastRank / bsr, 1.2), 0.01);
    }
    for (var i = 0; i < BSR_ANCHORS.length - 1; i++) {
      var r1 = BSR_ANCHORS[i][0];
      var s1 = BSR_ANCHORS[i][1];
      var r2 = BSR_ANCHORS[i + 1][0];
      var s2 = BSR_ANCHORS[i + 1][1];
      if (r1 <= bsr && bsr <= r2) {
        var logR1 = Math.log(r1);
        var logR2 = Math.log(r2);
        var logS1 = Math.log(s1);
        var logS2 = Math.log(s2);
        var t = (Math.log(bsr) - logR1) / (logR2 - logR1);
        return Math.exp(logS1 + t * (logS2 - logS1));
      }
    }
    return 0.0;
  }

  function printCostFor(fmt, pageCount) {
    var rule = PRINT_COST_RULES[fmt];
    if (!rule) return null;
    var pages = pageCount && pageCount > 0 ? pageCount : null;
    if (pages === null) return null; // never silently assume a page count
    if (pages <= rule.low_max_pages) return rule.fixed_low;
    return rule.fixed + rule.per_page * pages;
  }

  function estimateRoyaltyPerUnit(price, fmt, pageCount, ctx) {
    if (price <= 0) return 0.0;
    if (fmt === "Kindle") {
      // Optional per-marketplace 70% band + delivery fee (local currency).
      // When ctx is absent, the USD defaults keep this identical to before.
      var min = (ctx && ctx.tierMin != null) ? ctx.tierMin : 2.99;
      var max = (ctx && ctx.tierMax != null) ? ctx.tierMax : 9.99;
      var delivery = (ctx && ctx.deliveryFee != null) ? ctx.deliveryFee : 0.15;
      if (price >= min && price <= max) return Math.max(price * 0.7 - delivery, 0);
      return Math.max(price * 0.35, 0);
    }
    var cost = printCostFor(fmt, pageCount);
    if (cost === null) return null; // print royalty needs a page count
    return Math.max(price * 0.6 - cost, 0);
  }

  function competitionScore(reviewCount, bsr) {
    var reviewComponent = Math.min((reviewCount || 0) / 2000, 1.0) * 60;
    var bsrComponent = 0;
    if (bsr && bsr > 0) {
      bsrComponent = Math.max(0, (1 - Math.min(bsr, 200000) / 200000)) * 40;
    }
    var score = Math.round(reviewComponent + bsrComponent);
    score = Math.max(0, Math.min(100, score));
    var label = score < 30 ? "Low Competition" : score < 60 ? "Moderate Competition" : "High Competition";
    return { score: score, label: label };
  }

  function bankRound(x, decimals) {
    var factor = Math.pow(10, decimals);
    var scaled = x * factor;
    var floored = Math.floor(scaled);
    var diff = scaled - floored;
    if (diff < 0.5) return floored / factor;
    if (diff > 0.5) return (floored + 1) / factor;
    return (floored % 2 === 0 ? floored : floored + 1) / factor;
  }

  function keywordTokens(text) {
    var m = String(text || "").toLowerCase().match(/[a-z][a-z0-9'&+-]{1,}/g);
    return m || [];
  }

  function ngrams(tokens, n) {
    var out = [];
    for (var i = 0; i <= tokens.length - n; i++) out.push(tokens.slice(i, i + n).join(" "));
    return out;
  }

  function extractKeywords(data) {
    var sources = {
      Title: data.title || "",
      Subtitle: data.subtitle || "",
      Category: (data.categories || []).join(" > "),
    };
    var asinTok = String(data.asin || "").toLowerCase();
    var agg = new Map();
    var keys = Object.keys(sources);
    for (var si = 0; si < keys.length; si++) {
      var source = keys[si];
      var text = sources[source];
      if (!text) continue;
      var tokens = keywordTokens(text);
      var weight = SOURCE_WEIGHTS[source];
      var nOrder = [
        [2, 1.0],
        [1, 0.6],
      ];
      for (var oi = 0; oi < nOrder.length; oi++) {
        var n = nOrder[oi][0];
        var boost = nOrder[oi][1];
        var phrases = ngrams(tokens, n);
        for (var pi = 0; pi < phrases.length; pi++) {
          var words = phrases[pi].split(" ");
          if (asinTok && words.indexOf(asinTok) !== -1) continue;
          var hasStop = false;
          for (var wi = 0; wi < words.length; wi++) if (STOPWORDS.has(words[wi])) hasStop = true;
          if (hasStop) continue;
          var entry = agg.get(phrases[pi]);
          if (!entry) {
            entry = { count: 0, bestWeight: 0.0, sources: new Set() };
            agg.set(phrases[pi], entry);
          }
          entry.count += 1;
          entry.bestWeight = Math.max(entry.bestWeight, weight * boost);
          entry.sources.add(source);
        }
      }
    }

    var hits = [];
    var aggKeys = Array.from(agg.keys());
    for (var ai = 0; ai < aggKeys.length; ai++) {
      var keyword = aggKeys[ai];
      var e = agg.get(keyword);
      var confidence = 0.45 + 0.45 * e.bestWeight;
      if (e.sources.size > 1) confidence += 0.05;
      confidence = Math.min(0.95, confidence);
      var srcArr = Array.from(e.sources).sort();
      hits.push({
        keyword: keyword,
        source: srcArr.join(" / "),
        count: e.count,
        confidence: bankRound(confidence, 2),
      });
    }

    hits.sort(function (a, b) {
      if (a.confidence !== b.confidence) return b.confidence - a.confidence;
      if (a.count !== b.count) return b.count - a.count;
      return a.keyword < b.keyword ? -1 : a.keyword > b.keyword ? 1 : 0;
    });
    return hits.slice(0, 20);
  }

  function computeAnalytics(data, ctx) {
    var price = Number(data.price) || 0;
    var fmt = data.format || "Paperback";
    var pageCount = data.pageCount ? Number(data.pageCount) : null;
    var bsr = data.bsr ? Number(data.bsr) : 0;
    var reviewCount = data.reviewCount ? Number(data.reviewCount) : 0;
    var royaltyPerUnit = estimateRoyaltyPerUnit(price, fmt, pageCount, ctx);
    var dailySales = estimateDailySales(bsr);
    var monthlySales = dailySales * 30;
    var priceMissing = price <= 0;
    var pageCountMissing = fmt !== "Kindle" && !(pageCount && pageCount > 0);
    var royaltyUnknown = priceMissing || pageCountMissing;
    var dailyRoyalty = royaltyUnknown ? null : dailySales * royaltyPerUnit;
    var monthlyRoyalty = royaltyUnknown ? null : monthlySales * royaltyPerUnit;
    var grossMonthlyRevenue = monthlySales * price;
    var comp = competitionScore(reviewCount, bsr);
    var printCost = fmt === "Kindle" ? null : printCostFor(fmt, pageCount);
    return {
      royaltyPerUnit: royaltyPerUnit,
      dailySales: dailySales,
      monthlySales: monthlySales,
      dailyRoyalty: dailyRoyalty,
      monthlyRoyalty: monthlyRoyalty,
      grossMonthlyRevenue: grossMonthlyRevenue,
      comp: comp,
      priceMissing: priceMissing,
      pageCountMissing: pageCountMissing,
      royaltyUnknown: royaltyUnknown,
      printCost: printCost,
      keywords: extractKeywords(data),
    };
  }

  var api = {
    BSR_ANCHORS: BSR_ANCHORS,
    estimateDailySales: estimateDailySales,
    printCostFor: printCostFor,
    estimateRoyaltyPerUnit: estimateRoyaltyPerUnit,
    competitionScore: competitionScore,
    extractKeywords: extractKeywords,
    computeAnalytics: computeAnalytics,
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  } else {
    root.KDPEngine = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);